### ISSUE TITLE
Which to choose

### ISSUE THREAD

**Issue by XavRsl** [bikemike/easyappointments#7]
Hello,
I am about to use easy!appointment for the University I'm working for. I've installed the original version (alex's) but also found out that this fork appeared to be a bit more recent and seems to get some bug fixes. I'd like to know if you intend to ask for pull request to the main project so that it will get all the new stuff you implemented ? Do you have any interaction with Alex, the maintainer of the original project ?

Thanks.

Xavier

**Comment by bikemike** [comment]
I forked the project recently to make a few changes and I plan on creating a pull request when I'm done.

I have not had any interaction with Alex as of yet.

**Comment by XavRsl** [comment]
Thanks.
